[package]
name = "cityx"
version = "0.1.0"
authors = ["Whitekali <Discord: whitekali> <whitekali@aya.studio> <@251838559680593920>"]
edition = "2024"
description = "CityX - The Si'automaticion city 'x' procedural and modual game framework"
license = "MIT OR Apache-2.0"

# Workspace Definition
[workspace]
members = [
    "core", # Your core game logic
    "server", # Server-specific code
    "client", # Client-specific code (if applicable)
    "renderer", # Rendering engine 
    # ... add other modules as needed
]

# Core Crate (libcityx)
[dependencies]
matter = "matter-ecs/matter@0.8.3"
roact = "roblox/roact@1.4.0"
base64 = "reselim/base64@3.0.0" 
signal = "sleitnick/signal@2.0.1" 
trove = "sleitnick/trove@1.3.0" 
promise = "evaera/promise@4.0.0" 

# ... other core dependencies

# Server Crate 
[workspace.server]
members = ["server"]

[server.dependencies]
# ... server-specific dependencies

# Client Crate
[workspace.client]
members = ["client"]

[client.dependencies]
# ... client-specific dependencies

# Renderer Crate
[workspace.renderer]
members = ["renderer"]

[renderer.dependencies]
# ... rendering engine dependencies

# Development Dependencies
[dev-dependencies]
insta = { version = "1.1.0" } 

# Features
[features]
selene = [] 
wally = [] 
tools = ["wally", "selene"]
vendored-libgit2 = ["git2/vendored-libgit2"]

# Tooling
[tools]
wally = { source = "upliftgames/wally", version = "0.3.2" }
selene = { source = "Kampfkarren/selene", version = "0.22.0" }
