-- READ ME TO UNDERSTAND HOW TO MAKE FLOORS WORK! --
 
-------------------------------------------------------------
-- Step One: Check "Elevator Script", it will have something called "disasters =",
-- after this it will have something like this: "{"001","[Floor Name Here]",}, this
-- is your floor names, you can change the floor names, or add a new floor by naming
-- "001", "002", "003"... Once you added a floor name, go to step two.
--
-- Step Two: Now you need to make a floor, you a free to do YOUR floor!
--
-- Step Three: GROUP your floor, like a grouped model, after this, NAME your floor as a
-- NUMBER, like you did in the Step One, name your grouped floor as "002","003","004"...
--
-- Step Four: Put your GROUPED and NAMED floor at LIGHTNING, please CUT the model and
-- PASTE in LIGHTNING! >>"LIGHTNING"<<, NOT IN WORKSPACE!!! If you put the model in
-- another place, or delete, IT WILL NOT WORK, remember, LIGHTNING.
--
-- Step Five: If you want more floors in your game, repeat all steps here!
--
--
-- I HOPE I HELPED! IF IT WORKED, CREDIT ME IN YOUR GAME!
--
--
--
--
-- BY LAURITA425. ;D
--
-------------------------------------------------------------