name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ok-nick/setup-aftman@v0.3.0
        name: Install aftman

      - name: Lint
        run: |
          selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          args: --check ./src

  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3


      # Step 2: Install Wally using Homebrew (for dependency management)
      - name: Install Wally
        run: |
          # Install Homebrew
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          
          # Add Homebrew to PATH
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
          eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

          # Install Wally using Homebrew
          brew install wally


      # Step 3: Install Rojo
      - name: Install Rojo
        run: wally install rojo
