name: Build and Deploy to Roblox

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger for version tags, like v1.0.0
    branches:
      - mastvber

jobs:
  build-deploy:
    name: Build and Deploy Game to Roblox
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Install Wally using Homebrew (for dependency management)
      - name: Install Wally
        run: |
          # Install Homebrew
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          
          # Add Homebrew to PATH
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
          eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

          # Install Wally using Homebrew
          brew install wally

      # Step 3: Install Rojo
      - name: Install Rojo
        run: wally install rojo

      # Step 4: Install Roblox dependencies using Wally
      - name: Install Roblox dependencies with Wally
        run: wally install

      # Step 5: Verify Rojo installation
      - name: Verify Rojo Installation
        run: |
          rojo --version

      # Step 6: Build the game into .rbxl using Rojo
      - name: Build the game
        run: |
          mkdir -p Temp
          echo "Building ${GITHUB_REF}..."
          rojo build default.project.json --output Temp/CurrentBuild.rbxl

      # Step 7: Create a release on GitHub and upload the build (optional backup)
      - name: Create release and upload build
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Temp/CurrentBuild.rbxl
          asset_name: Build_${{ github.ref }}.rbxl
          asset_content_type: application/octet-stream

      # Step 8: Deploy to Roblox (Production)
      - name: Deploy to Roblox (Production)
        run: |
          echo "Deploying build to Roblox..."
          curl --verbose --location --request POST \
          'https://apis.roblox.com/universes/v1/${{ secrets.TEST_UNIVERSE_ID }}/places/${{ secrets.TEST_PLACE_ID }}/versions?versionType=Published' \
          --header "x-api-key:${{ secrets.API_KEY }}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @Temp/CurrentBuild.rbxl
        env:
          API_KEY: ${{ secrets.API_KEY }}
